//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Discounts
    {
        public Discounts()
        {
            this.GuestsDiscounts = new ObservableCollection<GuestsDiscounts>();
            this.Registration = new ObservableCollection<Registration>();
        }
    
        public int DiscountID { get; set; }
        public string DiscountTitle { get; set; }
        public int DiscountSize { get; set; }
        public Nullable<int> HotelID { get; set; }
    
        public virtual ObservableCollection<GuestsDiscounts> GuestsDiscounts { get; set; }
        public virtual ObservableCollection<Registration> Registration { get; set; }
        public virtual Hotels Hotels { get; set; }
    }
}
