//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class FreeRoomsView
    {
        public int RoomID { get; set; }
        public string RoomNum { get; set; }
        public Nullable<byte> NumberOfPlaces { get; set; }
        public Nullable<int> CostPerDay { get; set; }
        public string Type { get; set; }
    }
}
