//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class GuestsDiscounts
    {
        public int GuestsDisocuntsID { get; set; }
        public int DiscountID { get; set; }
        public int GuestID { get; set; }
    
        public virtual Discounts Discounts { get; set; }
        public virtual Guests Guests { get; set; }
    }
}
