//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Guests
    {
        public Guests()
        {
            this.GuestsDiscounts = new ObservableCollection<GuestsDiscounts>();
            this.Payment = new ObservableCollection<Payment>();
            this.ServiceRealization = new ObservableCollection<ServiceRealization>();
            this.Wishes = new ObservableCollection<Wishes>();
            this.Registration = new ObservableCollection<Registration>();
        }
    
        public int GuestID { get; set; }
        public string Name { get; set; }
        public string SecName { get; set; }
        public string ThirdName { get; set; }
        public string Address { get; set; }
        public string PassportData { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
    
        public virtual ObservableCollection<GuestsDiscounts> GuestsDiscounts { get; set; }
        public virtual ObservableCollection<Payment> Payment { get; set; }
        public virtual ObservableCollection<ServiceRealization> ServiceRealization { get; set; }
        public virtual ObservableCollection<Wishes> Wishes { get; set; }
        public virtual ObservableCollection<Registration> Registration { get; set; }
    }
}
