//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Hotels
    {
        public Hotels()
        {
            this.Discounts = new ObservableCollection<Discounts>();
            this.Payment = new ObservableCollection<Payment>();
            this.Registration = new ObservableCollection<Registration>();
            this.Rooms = new ObservableCollection<Rooms>();
            this.Wishes = new ObservableCollection<Wishes>();
            this.Services = new ObservableCollection<Services>();
        }
    
        public int HotelID { get; set; }
        public string HotelName { get; set; }
        public int HotelRating { get; set; }
        public string HotelAddress { get; set; }
    
        public virtual ObservableCollection<Discounts> Discounts { get; set; }
        public virtual ObservableCollection<Payment> Payment { get; set; }
        public virtual ObservableCollection<Registration> Registration { get; set; }
        public virtual ObservableCollection<Rooms> Rooms { get; set; }
        public virtual ObservableCollection<Wishes> Wishes { get; set; }
        public virtual ObservableCollection<Services> Services { get; set; }
    }
}
