//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BaseEntitiesContext : DbContext
    {
        public BaseEntitiesContext()
            : base("name=BaseEntitiesContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Discounts> Discounts { get; set; }
        public virtual DbSet<Guests> Guests { get; set; }
        public virtual DbSet<GuestsDiscounts> GuestsDiscounts { get; set; }
        public virtual DbSet<Payment> Payment { get; set; }
        public virtual DbSet<Rooms> Rooms { get; set; }
        public virtual DbSet<ServiceRealization> ServiceRealization { get; set; }
        public virtual DbSet<TypesOfRooms> TypesOfRooms { get; set; }
        public virtual DbSet<FreeRoomsView> FreeRoomsView { get; set; }
        public virtual DbSet<Wishes> Wishes { get; set; }
        public virtual DbSet<RegistrationView> RegistrationView { get; set; }
        public virtual DbSet<Registration> Registration { get; set; }
        public virtual DbSet<PaymentsView> PaymentsView { get; set; }
        public virtual DbSet<Hotels> Hotels { get; set; }
        public virtual DbSet<Services> Services { get; set; }
    }
}
