//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class PaymentsView
    {
        public int GuestID { get; set; }
        public string Name { get; set; }
        public string SecName { get; set; }
        public string ThirdName { get; set; }
        public Nullable<double> ServicesTotalCost { get; set; }
        public Nullable<int> RentCost { get; set; }
        public Nullable<double> TotalDebt { get; set; }
        public Nullable<double> Debt { get; set; }
        public int HotelID { get; set; }
    }
}
