//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Payment
    {
        public int PaymentID { get; set; }
        public double PaymentSize { get; set; }
        public System.DateTime PaymentDate { get; set; }
        public int GuestID { get; set; }
        public int HotelID { get; set; }
        public string PaymentComment { get; set; }
    
        public virtual Guests Guests { get; set; }
        public virtual Hotels Hotels { get; set; }
    }
}
