//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class RegistrationView
    {
        public int RegistrationID { get; set; }
        public Nullable<int> GuestID { get; set; }
        public Nullable<int> RoomID { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<System.DateTime> ExitDate { get; set; }
        public Nullable<int> HotelID { get; set; }
        public string Name { get; set; }
        public string SecName { get; set; }
        public string ThirdName { get; set; }
        public string RoomNum { get; set; }
        public Nullable<int> CostPerDay { get; set; }
        public string DiscountTitle { get; set; }
        public Nullable<int> DiscountSize { get; set; }
        public string Type { get; set; }
        public Nullable<int> TotalCost { get; set; }
    }
}
