//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Rooms
    {
        public Rooms()
        {
            this.Registration = new ObservableCollection<Registration>();
        }
    
        public int RoomID { get; set; }
        public string RoomNum { get; set; }
        public Nullable<byte> NumberOfPlaces { get; set; }
        public Nullable<int> TypeID { get; set; }
        public Nullable<int> CostPerDay { get; set; }
        public Nullable<int> HotelID { get; set; }
    
        public virtual TypesOfRooms TypesOfRooms { get; set; }
        public virtual ObservableCollection<Registration> Registration { get; set; }
        public virtual Hotels Hotels { get; set; }
    }
}
