//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class ServiceRealization
    {
        public int RealizationID { get; set; }
        public System.DateTime RealizationDate { get; set; }
        public int GuestID { get; set; }
        public int ServiceID { get; set; }
    
        public virtual Guests Guests { get; set; }
        public virtual Services Services { get; set; }
    }
}
