//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class TypesOfRooms
    {
        public TypesOfRooms()
        {
            this.Rooms = new ObservableCollection<Rooms>();
        }
    
        public int TypeID { get; set; }
        public string Type { get; set; }
    
        public virtual ObservableCollection<Rooms> Rooms { get; set; }
    }
}
