//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Wishes
    {
        public int WishID { get; set; }
        public string WishContent { get; set; }
        public Nullable<int> GuestID { get; set; }
        public int HotelID { get; set; }
        public string WishTitile { get; set; }
        public Nullable<System.DateTime> WishDate { get; set; }
    
        public virtual Guests Guests { get; set; }
        public virtual Hotels Hotels { get; set; }
    }
}
